export const FETCH_CONVERSATIONS_STARTED = 'FETCH_CONVERSATIONS_STARTED';
export const FETCH_CONVERSATIONS_ERROR = 'FETCH_CONVERSATIONS_ERROR';
export const FETCH_CONVERSATIONS_COMPLETED = 'FETCH_CONVERSATIONS_COMPLETED';

export const FETCH_MESSAGES_STARTED = 'FETCH_MESSAGES_STARTED';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const FETCH_MESSAGES_COMPLETED = 'FETCH_MESSAGES_COMPLETED';

export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA';
